# Generated by Django 5.2.2 on 2025-07-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='_state',
            new_name='state',
        ),
    ]
